POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Video node",
    "description": "Esse é o primeiro vídeo.",
    "duration": 180  
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/85c334df-896f-4890-8597-23088bc08ce7
Content-Type: application/json

{
    "title": "Video 2",
    "description": "Description 1",
    "duration": 180
}

###

DELETE http://localhost:3333/videos/85c334df-896f-4890-8597-23088bc08ce7